import { cn } from "@/lib/utils";
import { Sparkles, WifiOff } from "lucide-react";

export function AiStatus({ enabled, className }: { enabled: boolean; className?: string }) {
  return (
    <div
      className={cn(
        "flex items-start gap-2.5 rounded-lg border px-3.5 py-2.5 text-xs",
        enabled
          ? "border-signal-green/30 bg-signal-green/10 text-signal-green"
          : "border-signal-amber/30 bg-signal-amber/10 text-signal-amber",
        className,
      )}
    >
      {enabled ? <Sparkles className="mt-0.5 h-4 w-4 shrink-0" /> : <WifiOff className="mt-0.5 h-4 w-4 shrink-0" />}
      <p className="font-mono leading-relaxed">
        {enabled
          ? "Live AI · responses generated by Claude via the Anthropic API."
          : "Offline mode · deterministic fallback. Set ANTHROPIC_API_KEY in .env to enable Claude-powered output."}
      </p>
    </div>
  );
}
